<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KYUNGDUCK-PC" name="com.naver.main.kin.s01_지식iN홈.suite_01_지식iN홈_GNB_Test" tests="3" failures="0" timestamp="4 Aug 2014 08:37:12 GMT" time="13.559" errors="1">
  <testcase name="TC_02_GNB_지식iN_Test" time="2.446" classname="com.naver.main.kin.s01_지식iN홈.suite_01_지식iN홈_GNB_Test">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.naver.main.kin.s01_지식iN홈.suite_01_지식iN홈_GNB_Test.TC_02_GNB_지식iN_Test(suite_01_지식iN홈_GNB_Test.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
]]>
    </error>
  </testcase> <!-- TC_02_GNB_지식iN_Test -->
  <testcase name="TC_03_GNB_검색_Test" time="6.363" classname="com.naver.main.kin.s01_지식iN홈.suite_01_지식iN홈_GNB_Test"/>
  <testcase name="TC_01_GNB_NAVER_Test" time="4.750" classname="com.naver.main.kin.s01_지식iN홈.suite_01_지식iN홈_GNB_Test"/>
</testsuite> <!-- com.naver.main.kin.s01_지식iN홈.suite_01_지식iN홈_GNB_Test -->
